services:
  - type: web
    name: stock-market-digital-twin-backend
    env: python
    buildCommand: pip install -r modeling/requirements.txt
    startCommand: cd modeling && python -m uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
